### ISSUE TITLE
Could drone2 support subgroups like drone0.8

### ISSUE THREAD

**Issue by hasafox** [harness/drone#3293] opened 2022-12-01 03:20 UTC
I used drone0.8 and update to drone2 now, however I can't see my subgroups repo, but it is ok in drone0.8,  even it is ugly.
For example, I have a repo `/foo/bar/test.git`, in drone0.8 it shows like `/foo/bar` but I can search `foo/bar/test.git` in repos. However it is doesn't work in drone2, and I see this issue [2009](https://github.com/harness/drone/issues/2009). I like this function although it is ugly.

**Comment by bradrydzewski** [comment] 2023-01-17 14:53
closing this as duplicate of https://github.com/harness/drone/issues/2009

**Closed by bradrydzewski** 2023-01-17 14:53 UTC
